# Generated by Django 4.1 on 2023-09-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='image',
            field=models.ImageField(default='default_chef.png', upload_to='chefs'),
        ),
    ]
