# Generated by Django 4.1 on 2023-09-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_chef_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
