# Generated by Django 4.1 on 2023-09-03 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['categoryName']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['productName']},
        ),
        migrations.AddField(
            model_name='product',
            name='createdProduct',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='pastel_default.png', upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='modifiedProduct',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
